default: &default
  adapter: postgresql
  pool: <%= ENV['RAILS_MAX_THREADS'] { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: <%= ENV['PSQL_DATABASE'] %>_development

test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: <%= ENV['PSQL_DATABASE'] %>_test
  pool: 5
  username: <%= ENV['PSQL_USERNAME'] %>
  password: <%= ENV['PSQL_PASSWORD'] %>
  host: <%= ENV['PSQL_HOST'] %>

production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: <%= ENV['PSQL_DATABASE'] %>
  pool: 5
  username: <%= ENV['PSQL_USERNAME'] %>
  password: <%= ENV['PSQL_PASSWORD'] %>
  host: <%= ENV['PSQL_HOST'] %>
