default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DATABASE") %>_development

test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: <%= ENV.fetch("POSTGRES_DATABASE") %>_test
  pool: 5
  username: <%= ENV.fetch("POSTGRES_USERNAME") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>
  host: <%= ENV.fetch("POSTGRES_HOST") %>

production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: <%= ENV.fetch("POSTGRES_DATABASE") %>
  pool: 5
  username: <%= ENV.fetch("POSTGRES_USERNAME") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>
  host: <%= ENV.fetch("POSTGRES_HOST") %>