default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: MakoKamiya
  database: wsrm_development

test:
  <<: *default
  username: MakoKamiya
  database: wsrm_test

production:
  <<: *default
  database: wsrm
  username: postgres
  password: <%= ENV['WSRM_PSQL_APP_DATABASE_PASSWORD'] %>
